#!/bin/bash
#MNH_LIC Copyright 1994-2021 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt
#MNH_LIC for details. version 1.
##########################################################
#                                                        #
# ENVIRONEMMENT CONFIGURATION FOR MESONH                 #
#                                                        #
##########################################################
if [ "$SRC_MESONH" != "" ] 
then
##########################################################
#                                                        #
# ENVIRONEMENT MESONH ALLREADY SET                       #
#                                                        #
##########################################################
echo 
echo '--->' WARNING :: "profile_mesonh"
echo '--->' vous avez deja initialise votre variable d environnement '$SRC_MESONH'
echo '--->' '$SRC_MESONH="'$SRC_MESONH'"'
echo '--->' '"check your environnment profile_mesonh" !!!! '
echo 
fi
##########################################################
#                                                        #
# SOME SETTING FOR MESONH                                #
#                                                        #
##########################################################
#
# SRC_MESONH : default path to mesonh sources 
#              MUST BE SET TO YOUR OWN MESONH PATH
#
export SRC_MESONH="/Users/alonso-pinar_a/MNH-V5-6-0"   
#
#  Version MESONH PACKAGE :: PACK-MNH-V5-6-0 : 08/03/2023
#
export VERSION_XYZ=MNH-V5-6-0
#
#  Target Architecture/compiler Machine <=> Rules.*.mk files
#
#export ARCH=LXgfortran,LXifort,LXpgi,AIX64,SX8,BGQ
#
export ARCH=LXgfortran
#
#  Version of MPI
#
#export VER_MPI=MPIVIDE,MPIAUTO,MPIICE,MPIINTEL
#
export VER_MPI=MPIAUTO
#
# OPTIMIZATION LEVEL
#
#export OPTLEVEL=DEBUG,O2
#
export OPTLEVEL=O2
#
#  USER VERSION
#
export VER_USER=ORI
#
# 'Scandollar' Post Processing default variables
#
export CONF_DOLLAR=/Users/alonso-pinar_a/MNH-V5-6-0/conf/post/confdollar_aeropc_default
#
# Version of NETCDF / HDF
#
export VER_CDF=CDFAUTO
export VERSION_CDFC=4.9.0
export VERSION_CDFCXX=4.3.1
export VERSION_CDFF=4.6.0
export VERSION_HDF=1.14.0
export VERSION_LIBAEC=v1.0.6
#
# NETCDF4  INPUT/OUTPUT
#
export MNH_IOCDF4=1
#
# Version of GRIBAPI
#
export VER_GRIBAPI=
export VERSION_GRIBAPI=1.26.0-Source
#
# Version of ecCodes
#
export VERSION_ECCODES=2.18.0
export ECCODES_DEFINITION_PATH=/src/LIB/eccodes-2.18.0/definitions/
#
# Version of Def integer
#
export MNH_INT=4
export LFI_INT=8
#
# Version of Def Real
#
export MNH_REAL=8
#
#  Len of HREC characters 
#
export LEN_HREC=16
#
#  FOREFIRE
#
export MNH_FOREFIRE=1.0
#
#  RTTOV
#
export MNH_RTTOV=
export VER_RTTOV=
#
#  ECRAD
#
export MNH_ECRAD=
export VERSION_ECRAD=1.4.0
export VER_ECRAD=140
#
#  OASIS
#
export VER_OASIS=
#
# NCL_NCARG
#
export VERSION_NCL=
#
# MEGAN
#
export MNH_MEGAN=
#
#  Use MNH_EXPAND if VER_MNHEXP=MNHEXPAUTO
#
export VER_MNHEXP=MNHEXPAUTO
if [ "xMNHEXPAUTO" == "xMNHEXPAUTO" ] ;then
export VERSION_MNHEXP=MNH_EXPAND_1-2-2  
export VERSION_FILEPP=1.8.0
export FILEPP=${SRC_MESONH}/pub/FILEPP
export PATH=${FILEPP}/MNH_Expand_Array-${VERSION_MNHEXP}:${PATH}
export PATH=${FILEPP}/FILEPP-${VERSION_FILEPP}/bin:${PATH}
export MANPATH=${FILEPP}/FILEPP-${VERSION_FILEPP}/share/man:${MANPATH}
fi
##########################################################
##########################################################
##########################################################
#                                                        #
#    DONT MODIFY LINES AFTER THIS  !!!!!!!!!!!!!         #         
#                                                        #
##########################################################
##########################################################
##########################################################
#
export XYZ="-${ARCH}-R${MNH_REAL}I${MNH_INT}-${VERSION_XYZ}${MNH_ECRAD:+-ECRAD140}${MNH_FOREFIRE:+-FF}${VER_USER:+-${VER_USER}}-${VER_MPI}-${OPTLEVEL}"
#[ "x${VER_USER}" != "x" ] && export XYZ="${XYZ}-${VER_USER}"
# PATH to find tools like "makegen, etc ..."
export BIN_TOOLS=
export PATH=.:$SRC_MESONH/bin:$SRC_MESONH/exe:$SRC_MESONH/bin_tools:$SRC_MESONH/bin_tools/${BIN_TOOLS}:$PATH
#
# NCARG_ROOT : for use of graphic tools : diaprog 
# 
#  The "lib" and "bin" directory version 
#  are include in this package
#  ( and also the full pacakge , source etc... 
#    to be compiled for other plateforms )
#
export NCARG_ROOT=${NCARG_ROOT:-$SRC_MESONH/pub/${VERSION_NCL}}
export PATH=$PATH:$NCARG_ROOT/bin
# WARNING : NCARG Man not installed in that version
export MANPATH=$MANPATH:$NCARG_ROOT/man  
#
# VARTTY : for graphic tty console identification
#
export VARTTY=`tty`
#
# Variable depending on $ARCH 
#
[ -f ${SRC_MESONH}/conf/conf_${ARCH} ] && . ${SRC_MESONH}/conf/conf_${ARCH}

#
# Optional Environnement variable/Module  Env
#
 
